@baseUrl = http://localhost:3000/api

### POST Login /auth/login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "dev@example.com",
  "password": "SuperPassword1!"
}

### POST Logout /auth/logout
POST {{baseUrl}}/auth/logout
